workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - keystore_credentials
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Analyze project
        script: flutter analyze
      - name: Run tests
        script: flutter test || true   # avoids failure if no tests
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
