name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: stable

      - run: flutter pub get

      # 🔥 FIX: Replace "ONE" with "one" everywhere
      - name: Fix invalid project name everywhere
        run: |
          sed -i 's/ONE/one/g' pubspec.yaml || true
          sed -i 's/ONE/one/g' .metadata || true
          sed -i 's/ONE/one/g' android/settings.gradle || true
          sed -i 's/ONE/one/g' android/app/build.gradle || true

      - run: flutter create .

      - run: flutter build apk --release
      - run: flutter build appbundle --release

      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab
