- name: Create android folder if missing
  run: flutter create --platforms=android .

- name: Add Internet permission
  run: |
    sed -i '/<manifest/a\    <uses-permission android:name="android.permission.INTERNET" />' android/app/src/main/AndroidManifest.xml

- name: Build release APK
  run: flutter build apk --release
