name: Flutter Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      # 4. Clean + Recreate Android folder (forces V2 embedding)
      - name: Recreate Android folder with V2 embedding
        run: |
          rm -rf android
          flutter create .
          # Update app id and label
          sed -i 's/package="com.example.one"/package="com.adhimusic.app"/' android/app/src/main/AndroidManifest.xml
          sed -i 's/android:label="one"/android:label="AdhiMusic"/' android/app/src/main/AndroidManifest.xml

      # 5. Add extra permissions to AndroidManifest.xml (without overwriting)
      - name: Add permissions to AndroidManifest.xml
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"

          if [ ! -f "$MANIFEST" ]; then
            echo "❌ AndroidManifest.xml not found!"
            exit 1
          fi

          for PERM in \
            "android.permission.READ_EXTERNAL_STORAGE" \
            "android.permission.WRITE_EXTERNAL_STORAGE" \
            "android.permission.RECORD_AUDIO" \
            "android.permission.MODIFY_AUDIO_SETTINGS"
          do
            if ! grep -q "$PERM" "$MANIFEST"; then
              sed -i "/<manifest/a\    <uses-permission android:name=\"$PERM\"/>" "$MANIFEST"
            fi
          done

      # 6. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 7. Build APK
      - name: Build release APK
        run: flutter build apk --release

      # 8. Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
