name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Regenerate Android folder
      run: |
        echo "Removing old android folder..."
        rm -rf android
        flutter create . --platforms=android
        echo "✅ Android folder regenerated"

    - name: Patch app build.gradle (namespace + SDKs + Java/Kotlin)
      run: |
        APP_GRADLE="android/app/build.gradle"
        sed -i '/android {/a\    namespace "com.example.adhimusic"' $APP_GRADLE
        sed -i 's/compileSdkVersion [0-9]\+/compileSdkVersion 35/' $APP_GRADLE || true
        sed -i 's/targetSdkVersion [0-9]\+/targetSdkVersion 35/' $APP_GRADLE || true
        sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 21/' $APP_GRADLE || true
        sed -i '/android {/a\    compileOptions {\n        sourceCompatibility JavaVersion.VERSION_17\n        targetCompatibility JavaVersion.VERSION_17\n    }' $APP_GRADLE
        sed -i '/android {/a\    kotlinOptions {\n        jvmTarget = "17"\n    }' $APP_GRADLE
        echo "✅ Patched android/app/build.gradle"

    - name: Add permissions to AndroidManifest.xml
      run: |
        MANIFEST="android/app/src/main/AndroidManifest.xml"
        sed -i '/<application/i\
        <uses-permission android:name="android.permission.INTERNET"/>\n\
        <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>\n\
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>' $MANIFEST
        echo "✅ Added permissions"

    - name: Generate launcher icons
      run: flutter pub run flutter_launcher_icons

    - name: Build release APK
      run: flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
