name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      # 3️⃣ Install Android SDK 35 + build-tools (in home directory)
      - name: Install Android SDK 35
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          curl -o $HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q $HOME/cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platforms;android-35" "build-tools;35.0.1" "platform-tools"
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/cmdline-tools/bin:$PATH" >> $GITHUB_ENV

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5️⃣ Patch AndroidManifest.xml (permissions)
      - name: Patch AndroidManifest.xml
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i '/<application/i\
          <uses-permission android:name="android.permission.INTERNET"/>\n\
          <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>\n\
          <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>' $MANIFEST
          echo "✅ Patched AndroidManifest.xml with permissions"

      # 6️⃣ Generate launcher icons
      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons

      # 7️⃣ Build release APK
      - name: Build release APK
        run: flutter build apk --release

      # 8️⃣ Upload artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
