name: Flutter Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Flutter (stable, v3.13.9)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      # 3. Get dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # 4. Generate AndroidManifest.xml with required permissions
      - name: Generate AndroidManifest.xml
        run: |
          mkdir -p android/app/src/main
          cat <<EOT > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.adhimusic.app">

              <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
              <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
              <uses-permission android:name="android.permission.INTERNET"/>
              <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>

              <application
                  android:label="AdhiMusic"
                  android:icon="@mipmap/ic_launcher"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:allowBackup="true"
                  android:supportsRtl="true"
                  android:theme="@style/Theme.AdhiMusic">
                  
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/Theme.AdhiMusic"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:windowSoftInputMode="adjustResize">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOT

      # 5. Generate Android v2 MainActivity if missing
      - name: Generate MainActivity.kt
        run: |
          mkdir -p android/app/src/main/kotlin/com/adhimusic/app
          cat <<EOT > android/app/src/main/kotlin/com/adhimusic/app/MainActivity.kt
          package com.adhimusic.app

          import io.flutter.embedding.android.FlutterActivity

          class MainActivity: FlutterActivity() {
          }
          EOT

      # 6. Generate launcher icons automatically from assets/logo.png
      - name: Generate Launcher Icons
        run: flutter pub run flutter_launcher_icons:main

      # 7. Build release APK
      - name: Build APK
        run: flutter build apk --release

      # 8. Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
