name: Flutter Build APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: flutter/flutter-action@v2
        with:
          channel: stable

      # 3️⃣ Accept Android licenses
      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5️⃣ Generate Android folder if missing
      - name: Generate Android folder
        run: flutter create .

      # 6️⃣ Add required permissions to AndroidManifest.xml
      - name: Add permissions
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          # Backup original
          cp $MANIFEST $MANIFEST.bak
          
          # Check if manifest exists
          if [ -f "$MANIFEST" ]; then
            # Insert permissions after <manifest ...> line
            sed -i '/<manifest /a\
    <uses-permission android:name="android.permission.INTERNET" />\
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />\
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />' $MANIFEST
          fi

      # 7️⃣ Build APK
      - name: Build Release APK
        run: flutter build apk --release

      # 8️⃣ Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
