name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # ⚠️ Always regenerate android folder (forces V2 embedding)
      - name: Regenerate android folder
        run: |
          echo "⚠️ Removing old android/ folder and recreating..."
          rm -rf android
          flutter create . --platforms=android

      # ✅ Patch app/build.gradle with namespace + SDK versions
      - name: Patch app build.gradle
        run: |
          APP_GRADLE="android/app/build.gradle"
          sed -i '/android {/a\    namespace "com.example.adhimusic"' $APP_GRADLE
          sed -i 's/compileSdkVersion [0-9]\+/compileSdkVersion 35/' $APP_GRADLE || true
          sed -i 's/targetSdkVersion [0-9]\+/targetSdkVersion 35/' $APP_GRADLE || true
          sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 21/' $APP_GRADLE || true
          echo "✅ Patched android/app/build.gradle"

      # ✅ Fix plugin namespaces (for plugins missing namespace)
      - name: Patch plugin namespaces
        run: |
          find $HOME/.pub-cache -type f -path "*/android/build.gradle" | while read gradle; do
            if ! grep -q "namespace " "$gradle"; then
              pkg=$(basename $(dirname $gradle))
              echo "⚡ Adding namespace to $gradle"
              sed -i "/android {/a\    namespace \"com.plugin.$pkg\"" "$gradle"
            fi
          done
          echo "✅ Patched plugin namespaces"

      # ✅ Fix on_audio_query plugin manifest (remove old package attribute)
      - name: Patch on_audio_query plugin manifest
        run: |
          MANIFEST="$HOME/.pub-cache/hosted/pub.dev/on_audio_query_android-1.1.0/android/src/main/AndroidManifest.xml"
          if grep -q 'package=' "$MANIFEST"; then
            sed -i 's/package="com.lucasjosino.on_audio_query"//' "$MANIFEST"
            echo "✅ Removed invalid package attribute from on_audio_query_android manifest"
          fi

      # ✅ Patch AndroidManifest.xml with permissions + custom icon
      - name: Patch AndroidManifest.xml
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i '/<application/i\
          <uses-permission android:name="android.permission.INTERNET"/>\n\
          <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>\n\
          <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>' $MANIFEST
          sed -i 's/android:icon="@mipmap\/ic_launcher"/android:icon="@mipmap\/launcher_icon"/' $MANIFEST
          echo "✅ Patched AndroidManifest.xml"

      # ✅ Pin Gradle + AGP versions
      - name: Force Gradle + AGP versions
        run: |
          ROOT_GRADLE="android/build.gradle"
          sed -i 's/com.android.tools.build:gradle:[0-9.]\+/com.android.tools.build:gradle:8.3.2/' $ROOT_GRADLE || true
          echo "✅ Forced AGP 8.3.2"
          
          WRAPPER_PROPS="android/gradle/wrapper/gradle-wrapper.properties"
          sed -i 's/distributionUrl=.*$/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-8.7-bin.zip/' $WRAPPER_PROPS
          echo "✅ Forced Gradle 8.7"

      # ✅ Fix Kotlin + Java JVM target mismatch (force Java 17 everywhere)
      - name: Patch Gradle Java & Kotlin compatibility
        run: |
          APP_GRADLE="android/app/build.gradle"
          # Add Java 17 compatibility
          sed -i '/android {/a\    compileOptions {\n        sourceCompatibility JavaVersion.VERSION_17\n        targetCompatibility JavaVersion.VERSION_17\n    }' $APP_GRADLE
          # Add Kotlin JVM target 17
          sed -i '/android {/a\    kotlinOptions {\n        jvmTarget = "17"\n    }' $APP_GRADLE
          echo "✅ Forced Kotlin & Java to use JVM 17"

      # ✅ Generate launcher icons
      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons

      # ✅ Build APK
      - name: Build release APK
        run: flutter build apk --release

      # ✅ Upload artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
