name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable # choose Flutter stable version

      # 3️⃣ Enable Flutter web & cache dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # 4️⃣ Ensure android folder exists
      - name: Generate Android Folder if Missing
        run: |
          if [ ! -d "./android" ]; then
            flutter create .
          fi

      # 5️⃣ Write AndroidManifest.xml permissions
      - name: Write Android Permissions
        run: |
          mkdir -p android/app/src/main
          cat > android/app/src/main/AndroidManifest.xml <<EOL
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.adhimusic.app">

              <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
              <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
              <uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>
              <uses-permission android:name="android.permission.INTERNET"/>

              <application
                  android:label="AdhiMusic"
                  android:icon="@mipmap/ic_launcher">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOL

      # 6️⃣ Build APK release
      - name: Build Release APK
        run: flutter build apk --release

      # 7️⃣ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
