name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ Regenerate Android folder (forces V2 embedding)
      - name: Regenerate Android folder
        run: |
          echo "⚠️ Removing old android/ folder and recreating..."
          rm -rf android
          flutter create . --platforms=android

      # 5️⃣ Add permissions to AndroidManifest.xml
      - name: Add permissions
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i '/<application/i\
          <uses-permission android:name="android.permission.INTERNET"/>\n\
          <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>\n\
          <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>' $MANIFEST

      # 6️⃣ Set Gradle + Java/Kotlin versions
      - name: Set Gradle + Java + Kotlin
        run: |
          echo "org.gradle.jvmargs=-Xmx4096M" >> android/gradle.properties
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
          sed -i '/classpath "com.android.tools.build:gradle/s/$/"/' android/build.gradle || true

      # 7️⃣ Upgrade plugins to latest (important for v2 embedding)
      - name: Upgrade dependencies
        run: flutter pub upgrade --major-versions

      # 8️⃣ Build release APK
      - name: Build release APK
        run: flutter build apk --release

      # 9️⃣ Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
