name: Flutter Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"   # You can pin to your version

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Fix build.gradle (plugins + dependencies)
      - name: Patch build.gradle
        run: |
          # Ensure plugins exist at the top
          if ! grep -q "com.android.application" android/app/build.gradle; then
            sed -i '1i apply plugin: "com.android.application"' android/app/build.gradle
          fi
          if ! grep -q "kotlin-android" android/app/build.gradle; then
            sed -i '2i apply plugin: "kotlin-android"' android/app/build.gradle
          fi

          # Ensure dependencies block exists
          if ! grep -q "dependencies {" android/app/build.gradle; then
            echo -e "\ndependencies {\n}" >> android/app/build.gradle
          fi

          # Add required dependencies (skip duplicates)
          if ! grep -q "androidx.appcompat:appcompat" android/app/build.gradle; then
            sed -i '/dependencies {/a\    implementation "androidx.appcompat:appcompat:1.6.1"' android/app/build.gradle
          fi
          if ! grep -q "com.google.android.material:material" android/app/build.gradle; then
            sed -i '/dependencies {/a\    implementation "com.google.android.material:material:1.11.0"' android/app/build.gradle
          fi

      # 6. Build APK
      - name: Build release APK
        run: flutter build apk --release

      # 7. Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
