name: Flutter Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      # 3. Regenerate Android folder (ensures V2 embedding)
      - name: Regenerate Android folder
        run: |
          rm -rf android
          flutter create .

      # 4. Install dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # 4b. Patch app/build.gradle dependencies correctly
      - name: Patch build.gradle
        run: |
          # Ensure a dependencies block exists
          if ! grep -q "dependencies {" android/app/build.gradle; then
            echo -e "\ndependencies {\n}" >> android/app/build.gradle
          fi
          
          # Insert only inside the dependencies block
          awk '
            /dependencies[[:space:]]*{/ {
              print
              print "    implementation \"androidx.appcompat:appcompat:1.6.1\""
              print "    implementation \"com.google.android.material:material:1.11.0\""
              next
            }
            {print}
          ' android/app/build.gradle > android/app/build.gradle.new
          mv android/app/build.gradle.new android/app/build.gradle

      # 5. Generate AndroidManifest.xml with v2 embedding flag
      - name: Generate AndroidManifest.xml
        run: |
          mkdir -p android/app/src/main
          cat <<EOT > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.adhimusic.app">

              <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
              <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
              <uses-permission android:name="android.permission.INTERNET"/>
              <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>

              <application
                  android:label="AdhiMusic"
                  android:icon="@mipmap/ic_launcher"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:allowBackup="true"
                  android:supportsRtl="true"
                  android:theme="@style/Theme.AdhiMusic">

                  <!-- ✅ Force Android embedding V2 -->
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2"/>

                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/Theme.AdhiMusic"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:windowSoftInputMode="adjustResize">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOT

      # 6. Generate styles.xml (✅ Material3 + LaunchTheme)
      - name: Generate styles.xml
        run: |
          mkdir -p android/app/src/main/res/values
          cat <<EOT > android/app/src/main/res/values/styles.xml
          <resources>
              <!-- Main app theme -->
              <style name="Theme.AdhiMusic" parent="Theme.Material3.DayNight.NoActionBar">
                  <item name="android:windowFullscreen">false</item>
              </style>

              <!-- Launch screen theme -->
              <style name="LaunchTheme" parent="Theme.Material3.DayNight.NoActionBar">
                  <item name="android:windowBackground">@android:color/white</item>
              </style>
          </resources>
          EOT

      # 7. Generate launcher icons
      - name: Generate Launcher Icons
        run: flutter pub run flutter_launcher_icons:main

      # 8. Build APK
      - name: Build APK
        run: flutter build apk --release

      # 9. Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
