name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v3
      with:
        flutter-version: '3.13.0' # choose stable version

    - name: Install dependencies
      run: flutter pub get

    # --- Step: Ensure android folder exists ---
    - name: Generate Android folder if missing
      run: |
        if [ ! -d "android" ]; then
          flutter create .
        fi

    # --- Step: Write AndroidManifest.xml with permissions ---
    - name: Write AndroidManifest.xml
      run: |
        mkdir -p android/app/src/main
        cat > android/app/src/main/AndroidManifest.xml << EOL
        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
            package="com.adhimusic.app">

            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
            <uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>

            <application
                android:label="adhimusic"
                android:icon="@mipmap/ic_launcher">
                <activity
                    android:name=".MainActivity"
                    android:exported="true"
                    android:launchMode="singleTop"
                    android:theme="@style/LaunchTheme"
                    android:configChanges="keyboard|keyboardHidden|orientation|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                    android:hardwareAccelerated="true"
                    android:windowSoftInputMode="adjustResize">
                    <meta-data
                        android:name="io.flutter.embedding.android.NormalTheme"
                        android:resource="@style/NormalTheme"/>
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN"/>
                        <category android:name="android.intent.category.LAUNCHER"/>
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        EOL

    # --- Step: Generate launcher icons from assets/logo.png ---
    - name: Generate launcher icons
      run: flutter pub run flutter_launcher_icons:main

    # --- Step: Build release APK ---
    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
