name: Flutter Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Flutter (stable 3.10.6 for compatibility with Dart 3.0.6)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      # 3. Disable analytics to avoid prompts
      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      # 4. Install dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # 5. Generate launcher icons (your app logo)
      - name: Generate App Icons
        run: flutter pub run flutter_launcher_icons:main

      # 6. Ensure custom theme exists (Material2 for CI compatibility)
      - name: Create styles.xml
        run: |
          mkdir -p android/app/src/main/res/values
          cat <<EOT > android/app/src/main/res/values/styles.xml
          <resources>
              <style name="Theme.AdhiMusic" parent="Theme.AppCompat.Light.NoActionBar">
                  <item name="android:colorPrimary">@android:color/holo_blue_bright</item>
                  <item name="android:colorAccent">@android:color/holo_green_light</item>
              </style>
          </resources>
          EOT

      # 7. Generate AndroidManifest.xml with permissions & embedding v2
      - name: Generate AndroidManifest.xml
        run: |
          mkdir -p android/app/src/main
          cat <<EOT > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.adhimusic.app">

              <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
              <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
              <uses-permission android:name="android.permission.INTERNET"/>
              <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>

              <application
                  android:label="AdhiMusic"
                  android:icon="@mipmap/ic_launcher"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:allowBackup="true"
                  android:supportsRtl="true"
                  android:theme="@style/Theme.AdhiMusic">

                  <!-- Required for V2 embedding -->
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2" />

                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/Theme.AdhiMusic"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:windowSoftInputMode="adjustResize">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOT

      # 8. Build APK
      - name: Build APK
        run: flutter build apk --release

      # 9. Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
