name: Flutter Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      # 4. Clean + Recreate Android folder (forces V2 embedding)
      - name: Recreate Android folder with V2 embedding
        run: |
          rm -rf android
          flutter create .
          # Replace default app id and label
          sed -i 's/package="com.example.one"/package="com.adhimusic.app"/' android/app/src/main/AndroidManifest.xml
          sed -i 's/android:label="one"/android:label="AdhiMusic"/' android/app/src/main/AndroidManifest.xml

      # 5. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 6. Patch build.gradle with required deps
      - name: Patch build.gradle
        run: |
          if ! grep -q "dependencies {" android/app/build.gradle; then
            echo -e "\ndependencies {\n}" >> android/app/build.gradle
          fi
          if ! grep -q "androidx.appcompat:appcompat" android/app/build.gradle; then
            sed -i '/dependencies {/a\    implementation "androidx.appcompat:appcompat:1.6.1"' android/app/build.gradle
          fi
          if ! grep -q "com.google.android.material:material" android/app/build.gradle; then
            sed -i '/dependencies {/a\    implementation "com.google.android.material:material:1.11.0"' android/app/build.gradle
          fi

      # 7. Build APK
      - name: Build release APK
        run: flutter build apk --release

      # 8. Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
