name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Regenerate android folder
        run: |
          rm -rf android
          flutter create . --platforms=android

      # ✅ Fix app/build.gradle
      - name: Patch app build.gradle
        run: |
          APP_GRADLE="android/app/build.gradle"

          # Add namespace if not present
          if ! grep -q "namespace " $APP_GRADLE; then
            sed -i '/android {/a\    namespace "com.example.adhimusic"' $APP_GRADLE
          fi

          # Force SDK versions
          sed -i 's/compileSdkVersion [0-9]\+/compileSdkVersion 35/' $APP_GRADLE || true
          sed -i 's/targetSdkVersion [0-9]\+/targetSdkVersion 35/' $APP_GRADLE || true

          echo "✅ Patched android/app/build.gradle"

      # ✅ Fix project build.gradle (root)
      - name: Patch project build.gradle
        run: |
          PROJECT_GRADLE="android/build.gradle"

          # Ensure namespace for root project (some plugins rely on it)
          if ! grep -q "namespace " $PROJECT_GRADLE; then
            echo '
           allprojects {
             afterEvaluate { project ->
              if (project.plugins.hasPlugin("com.android.library") && !project.android.hasProperty("namespace")) {
            project.android.namespace = project.group.toString()
             }
           }
           }' >> $PROJECT_GRADLE
          fi

          echo "✅ Patched android/build.gradle"

      # ✅ Patch AndroidManifest.xml
      - name: Patch AndroidManifest.xml
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"

          sed -i '/<application/i\
          <uses-permission android:name="android.permission.INTERNET"/>\n\
          <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>\n\
          <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>' $MANIFEST

          sed -i 's/android:icon="@mipmap\/ic_launcher"/android:icon="@mipmap\/launcher_icon"/' $MANIFEST

          echo "✅ Patched AndroidManifest.xml"

      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
