name: Flutter Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Flutter (use 3.10.6 which is stable and works with subosito/flutter-action)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      # 3. Disable flutter analytics (avoid prompts)
      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      # 4. Regenerate android folder with V2 embedding
      - name: Regenerate Android Folder with V2 Embedding
        run: |
          rm -rf android
          flutter create .
          flutter pub get

      # 5. Ensure AndroidManifest.xml has required permissions
      - name: Generate AndroidManifest.xml
        run: |
          mkdir -p android/app/src/main
          cat <<EOT > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.adhimusic.app">

              <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
              <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
              <uses-permission android:name="android.permission.INTERNET"/>
              <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>

              <application
                  android:label="AdhiMusic"
                  android:icon="@mipmap/ic_launcher"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:allowBackup="true"
                  android:supportsRtl="true"
                  android:theme="@style/Theme.AdhiMusic">

                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/Theme.AdhiMusic"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:windowSoftInputMode="adjustResize">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOT

      # 6. Build APK
      - name: Build APK
        run: flutter build apk --release

      # 7. Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
