name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      # 3️⃣ Setup Android SDK 35 + Build-tools
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: 35.0.0
          ndk: none
          components: platform-tools

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5️⃣ Regenerate android folder (forces V2 embedding)
      - name: Regenerate android folder
        run: |
          echo "⚠️ Removing old android/ folder and recreating..."
          rm -rf android
          flutter create . --platforms=android

      # 6️⃣ Patch app build.gradle with namespace + SDK versions
      - name: Patch app build.gradle
        run: |
          APP_GRADLE="android/app/build.gradle"
          sed -i '/android {/a\    namespace "com.example.adhimusic"' $APP_GRADLE
          sed -i 's/compileSdkVersion [0-9]\+/compileSdkVersion 35/' $APP_GRADLE || true
          sed -i 's/targetSdkVersion [0-9]\+/targetSdkVersion 35/' $APP_GRADLE || true
          sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 21/' $APP_GRADLE || true
          echo "✅ Patched android/app/build.gradle"

      # 7️⃣ Patch all plugin namespaces (AGP 8+ requirement)
      - name: Patch all plugin namespaces
        run: |
          find $HOME/.pub-cache -type f -path "*/android/build.gradle" | while read gradle; do
            if ! grep -q "namespace " "$gradle"; then
              pkg=$(basename $(dirname $gradle))
              echo "⚡ Adding namespace to $gradle"
              sed -i "/android {/a\    namespace \"com.plugin.$pkg\"" "$gradle"
            fi
          done
          echo "✅ Patched all plugin namespaces"

      # 8️⃣ Patch on_audio_query plugin manifest
      - name: Patch on_audio_query plugin manifest
        run: |
          MANIFEST="$HOME/.pub-cache/hosted/pub.dev/on_audio_query_android-1.1.0/android/src/main/AndroidManifest.xml"
          if grep -q 'package=' "$MANIFEST"; then
            sed -i 's/package="com.lucasjosino.on_audio_query"//' "$MANIFEST"
            echo "✅ Removed invalid package attribute from on_audio_query_android manifest"
          fi

      # 9️⃣ Patch AndroidManifest.xml (permissions + icon)
      - name: Patch AndroidManifest.xml
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i '/<application/i\
          <uses-permission android:name="android.permission.INTERNET"/>\n\
          <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>\n\
          <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>' $MANIFEST
          sed -i 's/android:icon="@mipmap\/ic_launcher"/android:icon="@mipmap\/launcher_icon"/' $MANIFEST
          echo "✅ Patched AndroidManifest.xml"

      # 🔟 Patch Java + Kotlin compatibility
      - name: Patch Gradle Java & Kotlin compatibility
        run: |
          APP_GRADLE="android/app/build.gradle"
          # Java 17 for app
          sed -i '/android {/a\    compileOptions {\n        sourceCompatibility JavaVersion.VERSION_17\n        targetCompatibility JavaVersion.VERSION_17\n    }' $APP_GRADLE
          sed -i '/android {/a\    kotlinOptions {\n        jvmTarget = "17"\n    }' $APP_GRADLE
          
          # Java 17 for all plugins
          find $HOME/.pub-cache -type f -path "*/android/build.gradle" | while read gradle; do
            echo "⚡ Patching Java+Kotlin for $gradle"
            sed -i '/android {/a\    compileOptions {\n        sourceCompatibility JavaVersion.VERSION_17\n        targetCompatibility JavaVersion.VERSION_17\n    }' "$gradle"
            sed -i '/android {/a\    kotlinOptions {\n        jvmTarget = "17"\n    }' "$gradle"
          done
          echo "✅ Forced Java 17 + Kotlin JVM 17 everywhere"

      # 1️⃣1️⃣ Generate launcher icons
      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons

      # 1️⃣2️⃣ Build release APK
      - name: Build release APK
        run: flutter build apk --release

      # 1️⃣3️⃣ Upload artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
